language: node_js
node_js:
  - '6'
  - '8'
  - '10'
deploy:
  provider: script
  script: ./node_modules/.bin/nlm release
  skip_cleanup: true
  'on':
    branch: master
    node: '8'
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - oracle-java8-set-default
